### ISSUE TITLE
Missing linux/unix/osx support

### ISSUE THREAD

**Issue by Byron** [DanielKeep/cargo-script#1]
This issue is just meant to be a place to track progress on implementing the platform specific requirements to make `cargo-script` work on non-windows platforms.

Even though I have no intention on implementing it myself, I would like to try `cargo-script` when it runs on OSX as well.

**Comment by DanielKeep** [comment]
Currently, the other thing that really needs modification is `platform::inner::get_cache_dir_for`.  I haven't checked to see *exactly* where Cargo puts things, but *presumably* it's something like `$HOME/.cargo`.

The major reason I haven't is that I can't be bothered to set up a linux VM for testing right now.

There is one thing that *does* need some work: how to invoke `cargo script` from a hashbang.  My vague recollection is that `#!/usr/bin/env cargo script` will be invoked as `/usr/bin/env "cargo script" "$0"`, so that won't work.  Annoyingly, `cargo` passes the complete command-line to sub-commands, so what `cargo-script` gets for `cargo script X` is `cargo-script script X`, which means the hashbang would have to add a `script` argument and *blech*.

So a *nix version will probably want some kind of wrapper around `cargo script`, too.

**Comment by withoutboats** [comment]
cargo does put things in ~/.cargo

**Comment by Byron** [comment]
Awesome, thanks !

**Comment by DanielKeep** [comment]
@Byron: Thanks should be directed to @Ryman who implemented it. :)
