### ISSUE TITLE
-d and -e don't work together

### ISSUE THREAD

**Issue by durka** [DanielKeep/cargo-script#8]
...since you can't put an "extern crate" statement in an expression (edit: I mean, you _can_, but it is [silently ignored](http://is.gd/8dMeRP)). A fix might be to automatically inject the extern statements in expr.rs when -d and -e are both present.

**Comment by DanielKeep** [comment]
What?  A user?  *Whence came you?*

The problem is that there's no guarantee that the name of the package and the name of the crate have *anything* to do with one another.  So this would merely create the problem of "when I try to use dependency `X`, cargo script fails to compile for no reason"... which is admittedly less *often*, but I prefer proper fixes rather than frequency-based ones.

The *real* solution is to properly integrate with Cargo; ask it to parse and resolve the manifest, then tell us the name of the lib crate exported by a package.  The problem with *this* is that Cargo is a tangled mess of indirection that I'm in *no hurry* to face again.

There was a fork of cargo script a while back that tried to solve this by running cargo build with `-v`, then parsing the command line it passed to rustc to find out what the crates were called so that if the compile failed, it could adjust the extern statements to pull the crates in... which didn't *entirely* work because Cargo doesn't correctly escape shell commands when it *displays* them, and that code didn't correctly parse them *and* didn't deal with all options, since I *suspect* rustc's command line interface is non-regular (*i.e.* you could "escape" what looks like an argument with a different argument), but I'm not sure about that.

I agree with the issue's title, I'm just not entire sure what the best solution is.

**Comment by durka** [comment]
> The problem is that there's no guarantee that the name of the package and the name of the crate have anything to do with one another.

Wait, really? I thought they were the same, modulo underscores.

**Comment by DanielKeep** [comment]
Take `user32-sys`, which exports a crate `user32`.  Oh sure, they *usually* match, but they *don't have to*.

**Comment by durka** [comment]
Sifting through `target/release/deps/lib$CRATE-xxxxxx.rlib` might work.

**Comment by durka** [comment]
[This](https://github.com/brson/cargo-crusader/blob/master/src/main.rs#L107) seems rather relevant!

**Comment by durka** [comment]
Another idea, akin to the fork you mentioned above: run the build with `$RUSTC` set to a script that does nothing but collect `--extern` arguments!

**Comment by DanielKeep** [comment]
Well, scanning the `target/*/deps` folder doesn't work: it includes transitive dependencies that Cargo doesn't expose to the root package.

I really, really, *really* don't want to mess around with trying to intercede the build process with fake programs.  The viable solutions for this are becoming increasingly asinine.  It should *not* be this hard.

**Comment by durka** [comment]
Yep, definitely a hack, though maybe not the worst one ever :) . The "right" solution seems like

1. Parse Cargo.toml to get the dependencies
2. Find the dependencies and run something like the `get_crate_name` function linked above
3. Generate a bunch of extern crate statements.

It's step 2 that I have no idea how to do, because Cargo hides the dependencies away in the cache in a directory named with a (random?) hash, and if multirust is in play the cache is even harder to find. Maybe there is a way to force Cargo to use an alternate crate cache?

**Comment by durka** [comment]
Actually, one could try isolating Cargo (set `$CARGO_HOME`) like multirust does...

**Comment by DanielKeep** [comment]
`get_crate_name` only works if you already know where the manifest is.  It's *finding* the manifest that's the problem.

All I need is some way to just *ask* Cargo for this information.

And isolating Cargo would make running scripts *even more* painful, since now it's got to completely re-download the index and the dependencies for *every single script*.

For context, I just spent two hours waiting for a fresh `cargo fetch` to finish.

**Comment by durka** [comment]
Yeah, that's bad. It's really unfortunate that (a) there's no `cargo deps` command, and (b) the cache is hidden. Cargo is at least 300% too opinionated of a buid system, IMO.

**Comment by DanielKeep** [comment]
Relevant: rust-lang/cargo#1098

**Comment by DanielKeep** [comment]
The new `-D` and `-x` switches are probably about as good as things are going to get unless Cargo itself gets smarter.  I consider them "good enough" to consider this taken care of.

**Comment by durka** [comment]
:+1:
